services:
  db:
    image: postgres:17-alpine
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  cache:
    image: redis:8-alpine
    container_name: cache-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis:/data
      - ./src/core/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro

volumes:
  postgres:
  redis:
