/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as appSharedIndexRouteImport } from './routes/(app)/shared/index'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as appFilesIndexRouteImport } from './routes/(app)/files/index'
import { Route as appFileActivityIndexRouteImport } from './routes/(app)/file-activity/index'
import { Route as adminUsersIndexRouteImport } from './routes/(admin)/users/index'
import { Route as adminGroupsIndexRouteImport } from './routes/(admin)/groups/index'
import { Route as adminAlertsIndexRouteImport } from './routes/(admin)/alerts/index'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const appSharedIndexRoute = appSharedIndexRouteImport.update({
  id: '/shared/',
  path: '/shared/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appRouteRoute,
} as any)
const appFilesIndexRoute = appFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => appRouteRoute,
} as any)
const appFileActivityIndexRoute = appFileActivityIndexRouteImport.update({
  id: '/file-activity/',
  path: '/file-activity/',
  getParentRoute: () => appRouteRoute,
} as any)
const adminUsersIndexRoute = adminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminGroupsIndexRoute = adminGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAlertsIndexRoute = adminAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => adminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/alerts/': typeof adminAlertsIndexRoute
  '/groups/': typeof adminGroupsIndexRoute
  '/users/': typeof adminUsersIndexRoute
  '/file-activity/': typeof appFileActivityIndexRoute
  '/files/': typeof appFilesIndexRoute
  '/settings/': typeof appSettingsIndexRoute
  '/shared/': typeof appSharedIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/register/': typeof authRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '/alerts': typeof adminAlertsIndexRoute
  '/groups': typeof adminGroupsIndexRoute
  '/users': typeof adminUsersIndexRoute
  '/file-activity': typeof appFileActivityIndexRoute
  '/files': typeof appFilesIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/shared': typeof appSharedIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/(admin)/alerts/': typeof adminAlertsIndexRoute
  '/(admin)/groups/': typeof adminGroupsIndexRoute
  '/(admin)/users/': typeof adminUsersIndexRoute
  '/(app)/file-activity/': typeof appFileActivityIndexRoute
  '/(app)/files/': typeof appFilesIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(app)/shared/': typeof appSharedIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts/'
    | '/groups/'
    | '/users/'
    | '/file-activity/'
    | '/files/'
    | '/settings/'
    | '/shared/'
    | '/login/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/groups'
    | '/users'
    | '/file-activity'
    | '/files'
    | '/settings'
    | '/shared'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/(admin)'
    | '/(app)'
    | '/(auth)'
    | '/(app)/'
    | '/(admin)/alerts/'
    | '/(admin)/groups/'
    | '/(admin)/users/'
    | '/(app)/file-activity/'
    | '/(app)/files/'
    | '/(app)/settings/'
    | '/(app)/shared/'
    | '/(auth)/login/'
    | '/(auth)/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminRouteRoute: typeof adminRouteRouteWithChildren
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/shared/': {
      id: '/(app)/shared/'
      path: '/shared'
      fullPath: '/shared/'
      preLoaderRoute: typeof appSharedIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/files/': {
      id: '/(app)/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof appFilesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/file-activity/': {
      id: '/(app)/file-activity/'
      path: '/file-activity'
      fullPath: '/file-activity/'
      preLoaderRoute: typeof appFileActivityIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(admin)/users/': {
      id: '/(admin)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof adminUsersIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/groups/': {
      id: '/(admin)/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof adminGroupsIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/alerts/': {
      id: '/(admin)/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof adminAlertsIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminAlertsIndexRoute: typeof adminAlertsIndexRoute
  adminGroupsIndexRoute: typeof adminGroupsIndexRoute
  adminUsersIndexRoute: typeof adminUsersIndexRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAlertsIndexRoute: adminAlertsIndexRoute,
  adminGroupsIndexRoute: adminGroupsIndexRoute,
  adminUsersIndexRoute: adminUsersIndexRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appFileActivityIndexRoute: typeof appFileActivityIndexRoute
  appFilesIndexRoute: typeof appFilesIndexRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
  appSharedIndexRoute: typeof appSharedIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appFileActivityIndexRoute: appFileActivityIndexRoute,
  appFilesIndexRoute: appFilesIndexRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
  appSharedIndexRoute: appSharedIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminRouteRoute: adminRouteRouteWithChildren,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
